version: '3'
services:
  postgres:
    image: "postgres:13-alpine"
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - custom-net
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - pgdata:/var/lib/postgresql/data

  node-app:
    image: v0f/node-app
    profiles:
      - nodeInDocker
    build:
      context: .
      dockerfile: node.Dockerfile
    # working_dir: /app
    depends_on:
        - postgres
    networks:
      - custom-net
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT
      - POSTGRES_HOSTNAME=postgres
    restart: always
    init: true
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
volumes:
  pgdata:
networks:
  custom-net:
    driver: bridge
